[book]
authors = ["Arman Riazi"]
language = "en"
multilingual = false
src = "./workspace/"
title = "Rust-All-In-One"

[rust]
edition = "2021"   # the default edition for code blocks


[build]
# extra-watch-dirs = ["./workspace"]

# [output.html]
# theme = "my-theme"
# default-theme = "light"
# preferred-dark-theme = "navy"
# curly-quotes = true
# mathjax-support = false
# copy-fonts = true
# additional-css = ["rust/assets/css/custom.css"]
# additional-js = ["rust/assets/js/custom.js"]
# no-section-label = false
git-repository-url = "https://github.com/armanriazi/rust-all-in-one"
git-repository-icon = "fa-github"
# edit-url-template = "https://github.com/armanriazi/rust-all-in-one/edit/main/workspace"
site-url = "/rust-all-in-one/"
# cname = "main.rs"
# input-404 = "not-found.md"

[output.html]
site-url = "/rust-all-in-one/"
