[package]
name = "rust-all-in-one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [


    "workspace/shared",

    "workspace/documentation/knoldus/knoldus_bin",
    "workspace/documentation/knoldus/knoldus_lib",

    "workspace/feature/rust-doc/mod_draw_bin",
    "workspace/feature/rust-doc/mod_draw_lib",
    "workspace/feature/code-like-pro/dryoc_bin",


    "workspace/projects/fuzzme/fuzz_bin",
    "workspace/projects/fuzzme/fuzz_lib",

    "workspace/data/rust-in-action/csv_bin",

    "workspace/lifetime/dangling/rust-doc",
    "workspace/lifetime/dangling/rust-egg",
    "workspace/lifetime/dangling/rust-in-action",

    "workspace/thread/race/rust-in-action",

    "workspace/data/convert/try_into/rust-in-action",

    "workspace/types/primitive/float/rust-in-action",
    "workspace/types/primitive/char/rust-egg",
    "workspace/types/primitive/array/rust-egg",
    "workspace/types/primitive/tuple/rust-egg",
    "workspace/types/primitive/int/code-like-a-pro",
    "workspace/types/primitive/int/rust-in-action",
    "workspace/types/primitive/int/num/rust-in-action",
    "workspace/types/primitive/operator/rust-in-action",
    "workspace/types/primitive/radix/rust-in-action",
    "workspace/types/complex/num/rust-in-action",

    "workspace/flowcontrol/for/rust-in-action",
    "workspace/flowcontrol/while/rust-in-action",

]
