[toolchain]
channel = "stable-x86_64-unknown-linux-gnu"
#channel = "x86_64-pc-windows-gnu"
components = [ "rustfmt", "rustc-dev","clippy"]
# targets = [ "x86_64-unknown-linux-gnu", "wasm32-unknown-unknown" ]
targets = [ "x86_64-pc-windows-msvc","x86_64-pc-windows-gnu", "wasm32-unknown-unknown" ]
profile = "minimal"

[rust]
lld = true
