[package]
name = "rust-doc-trait-associate-type_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "rust-doc-trait-associate-type-main"
path = "src/rust-doc-trait-associate-type-main.rs"
