name: Rust
on: [ push ]
permissions: write-all
jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Program
      run: cargo run
