name: Rust
on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Program
      run: cargo run
